name : Build image docker
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-docker-iamge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - name: Cancel previous pipeline
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GHCR }}
          all_but_latest: true
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/doctorhoai/cicd
          flavor: latest=true
          tags: |
            type=raw,value=deploy-{{sha}}
      - name: Login to image repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: 'true'
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            IMAGE_TAG=qa-deploy-${{ github.sha }}
            RELEASE_TAG=${{ github.event.pull_request.number }}